### ISSUE TITLE
throws exceptions. does not work

### ISSUE THREAD

**Issue by consigliory** [RoushTech/RollbarDotNet#28]
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at RollbarDotNet.Core.ServiceExtensions.AddRollbarWeb(IServiceCollection services, IConfigurationRoot configuration)
   at Uqualio.Startup.ConfigureServices(IServiceCollection services)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Uqualio.Program.Main(String[] args)

**Comment by StrangeWill** [comment]
Never got this up to date after the RC2 release, will see about getting that done today.

**Comment by StrangeWill** [comment]
Already documented as #25

**Comment by StrangeWill** [comment]
@consigliory 0.4.0 was released to Nuget a few minutes ago, tested it on my newer .NET Core 1.0 apps and it seemed fine (and of course tests passed).
